#!/usr/bin/env bash
# =============================================================================
# sync-site.sh — import a site snapshot from the Hetzner storage box.
#
# Pulls the directory in HETZNER_SYNC_SRC (a dated snapshot like
# /home/pressabl/2026-08-27/spam-destroyer.com) into HETZNER_SYNC_DEST
# (/var/www/...) on every deploy, keeping it in sync with the snapshot.
#
# Config comes from .env (see .env.example):
#   HETZNER_SYNC_USER   storage box user, e.g. u513410
#   HETZNER_SYNC_HOST   e.g. u513410.your-storagebox.de
#   HETZNER_SYNC_PORT   usually 23
#   HETZNER_SYNC_KEY    SSH key for the box (generated by host-setup.sh)
#   HETZNER_SYNC_SRC    remote snapshot dir (empty = disabled)
#   HETZNER_SYNC_DEST   local destination
#
# One-time step: the PUBLIC key must be authorized on the box once. Hetzner
# storage boxes install a key with:
#     cat <key>.pub | ssh -p <port> <user>@<host> install-ssh-key
# (it asks for the storage box password). When run interactively (from a
# deploy) this offers to run that for you, then retries the import; 's' skips
# it. Non-interactive runs just fail with the instructions.
#
#   sudo ./scripts/sync-site.sh     (also called automatically by deploy.sh)
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."
[ -f .env ] && set -a && source .env && set +a

SRC="${HETZNER_SYNC_SRC:-}"
DEST="${HETZNER_SYNC_DEST:-}"
USER="${HETZNER_SYNC_USER:-}"
HOST="${HETZNER_SYNC_HOST:-}"
PORT="${HETZNER_SYNC_PORT:-23}"
KEY="${HETZNER_SYNC_KEY:-/home/ryan/.ssh/hetzner_backup}"

if [ -z "$SRC" ] || [ -z "$DEST" ] || [ -z "$USER" ] || [ -z "$HOST" ]; then
  echo "HETZNER_SYNC_* not configured in .env — skipping site import."
  exit 0
fi

if [ ! -f "$KEY" ]; then
  echo "!! Missing SSH key $KEY"
  echo "   Run: sudo bash scripts/host-setup.sh   (generates the key and prints the .pub)"
  exit 1
fi

run_sync() {
  # BatchMode=yes: never prompt for a password — an unauthorized key fails
  # fast so we can show the "add the key" instructions instead of hanging.
  rsync -az --delete \
    --exclude='*.log' \
    --exclude='.cache' \
    --exclude='lost+found' \
    -e "ssh -i $KEY -p $PORT -o BatchMode=yes -o StrictHostKeyChecking=accept-new" \
    "$USER@$HOST:$SRC/" "$DEST/"
}

echo "==> importing $USER@$HOST:$SRC -> $DEST"
mkdir -p "$DEST"

if ! run_sync; then
  echo
  echo "!! The Hetzner box rejected the connection — the SSH key is not"
  echo "   authorized on it yet (one-time step):"
  echo
  echo "   Public key:"
  echo "     $(cat "$KEY.pub" 2>/dev/null || echo "(key not readable)")"
  echo
  echo "   Install it on the box with (asks for the storage box password):"
  echo "     cat $KEY.pub | ssh -p $PORT $USER@$HOST install-ssh-key"
  echo

  install_key() {
    echo "==> Installing the key on $HOST (enter the storage box password when asked)..."
    cat "$KEY.pub" | ssh -p "$PORT" -o StrictHostKeyChecking=accept-new \
      "$USER@$HOST" install-ssh-key
  }

  if [ -t 0 ]; then
    attempts=0
    while [ "$attempts" -lt 5 ]; do
      read -r -p "Authorize the key on the box now? [Y/n] (s = skip the import): " answer
      case "${answer,,}" in
        s|skip)
          echo "Skipping site import. (Run 'sudo bash scripts/sync-site.sh' later to re-sync.)"
          exit 0
          ;;
        n|no)
          echo "   OK — skipping the key install; retrying the import anyway."
          ;;
        *)
          if install_key; then
            echo "==> Key installed — retrying the import."
          else
            echo "!! install-ssh-key failed (wrong password? box unreachable?). Retrying anyway."
          fi
          ;;
      esac
      if run_sync; then
        "$PWD/scripts/fix-perms.sh" "$DEST"
        echo "Imported."
        exit 0
      fi
      echo "!! Still rejected — the key still isn't authorized on the box."
      attempts=$((attempts + 1))
    done
    echo "Giving up after $attempts attempts — continuing without the import."
    exit 1
  else
    echo "   (not interactive — install the key, then re-run:"
    echo "    sudo bash scripts/sync-site.sh)"
    echo "    e.g.  cat $KEY.pub | ssh -p $PORT $USER@$HOST install-ssh-key"
    exit 1
  fi
fi

"$PWD/scripts/fix-perms.sh" "$DEST"
echo "Imported."