#!/usr/bin/env bash
# =============================================================================
# sync-site.sh — import a site snapshot from the Hetzner storage box.
#
# Pulls the directory in HETZNER_SYNC_SRC (a dated snapshot like
# /home/pressabl/2026-08-27/spam-destroyer.com) into HETZNER_SYNC_DEST
# (/var/www/...) on every deploy, keeping it in sync with the snapshot.
#
# Config comes from .env (see .env.example):
#   HETZNER_SYNC_USER   storage box user, e.g. u513410
#   HETZNER_SYNC_HOST   e.g. u513410.your-storagebox.de
#   HETZNER_SYNC_PORT   usually 23
#   HETZNER_SYNC_KEY    SSH key for the box (generated by host-setup.sh)
#   HETZNER_SYNC_SRC    remote snapshot dir (empty = disabled)
#   HETZNER_SYNC_DEST   local destination
#
# One-time manual step: the PUBLIC key must be authorized on the box
# (Hetzner Robot -> Storage Box -> SSH keys, or place it in the box's
# ~/.ssh/authorized_keys via sftp). When run interactively (from a deploy)
# this stops and waits for you to do that, then retries on Enter, or lets you
# skip with 's'. Non-interactive runs just fail with the instructions.
#
#   sudo ./scripts/sync-site.sh     (also called automatically by deploy.sh)
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."
[ -f .env ] && set -a && source .env && set +a

SRC="${HETZNER_SYNC_SRC:-}"
DEST="${HETZNER_SYNC_DEST:-}"
USER="${HETZNER_SYNC_USER:-}"
HOST="${HETZNER_SYNC_HOST:-}"
PORT="${HETZNER_SYNC_PORT:-23}"
KEY="${HETZNER_SYNC_KEY:-/home/ryan/.ssh/hetzner_backup}"

if [ -z "$SRC" ] || [ -z "$DEST" ] || [ -z "$USER" ] || [ -z "$HOST" ]; then
  echo "HETZNER_SYNC_* not configured in .env — skipping site import."
  exit 0
fi

if [ ! -f "$KEY" ]; then
  echo "!! Missing SSH key $KEY"
  echo "   Run: sudo bash scripts/host-setup.sh   (generates the key and prints the .pub)"
  exit 1
fi

run_sync() {
  # BatchMode=yes: never prompt for a password — an unauthorized key fails
  # fast so we can show the "add the key" instructions instead of hanging.
  rsync -az --delete \
    --exclude='*.log' \
    --exclude='.cache' \
    --exclude='lost+found' \
    -e "ssh -i $KEY -p $PORT -o BatchMode=yes -o StrictHostKeyChecking=accept-new" \
    "$USER@$HOST:$SRC/" "$DEST/"
}

echo "==> importing $USER@$HOST:$SRC -> $DEST"
mkdir -p "$DEST"

if ! run_sync; then
  echo
  echo "!! The Hetzner box rejected the connection — the SSH key is not"
  echo "   authorized on it yet (one-time, manual):"
  echo
  echo "   1. Paste this PUBLIC key into the box:"
  echo "        Hetzner Robot -> Storage Box -> $USER -> SSH keys"
  echo "        $(cat "$KEY.pub" 2>/dev/null || echo "(key not readable)")"
  echo "      (or one-time: sftp -P $PORT $USER@$HOST and place the .pub"
  echo "       in ~/.ssh/authorized_keys)"
  echo

  if [ -t 0 ]; then
    attempts=0
    while [ "$attempts" -lt 5 ]; do
      read -r -p "Press Enter once the key is added to the Hetzner box to retry, or 's' to skip the import: " answer
      case "$answer" in
        s|S|skip)
          echo "Skipping site import. (Run 'sudo bash scripts/sync-site.sh' later to re-sync.)"
          exit 0
          ;;
        "")
          if run_sync; then
            "$PWD/scripts/fix-perms.sh" "$DEST"
            echo "Imported."
            exit 0
          fi
          echo "!! Still rejected — the key hasn't been added yet?"
          attempts=$((attempts + 1))
          ;;
        *)
          echo "   ('s' = skip, or just press Enter to retry)"
          ;;
      esac
    done
    echo "Giving up after $attempts attempts — continuing without the import."
    exit 1
  else
    echo "   (not interactive — authorize the key, then re-run:"
    echo "    sudo bash scripts/sync-site.sh)"
    exit 1
  fi
fi

"$PWD/scripts/fix-perms.sh" "$DEST"
echo "Imported."