#!/usr/bin/env bash
# =============================================================================
# sync-site.sh — import a site snapshot from the Hetzner storage box.
#
# Pulls the directory in HETZNER_SYNC_SRC (a dated snapshot like
# /home/pressabl/2026-08-27/spam-destroyer.com) into HETZNER_SYNC_DEST
# (/var/www/...) on every deploy, keeping it in sync with the snapshot.
#
# Config comes from .env (see .env.example):
#   HETZNER_SYNC_USER   storage box user, e.g. u513410
#   HETZNER_SYNC_HOST   e.g. u513410.your-storagebox.de
#   HETZNER_SYNC_PORT   usually 23
#   HETZNER_SYNC_KEY    SSH key for the box (generated by host-setup.sh)
#   HETZNER_SYNC_SRC    remote snapshot dir (empty = disabled)
#   HETZNER_SYNC_DEST   local destination
#
# One-time manual step: the PUBLIC key must be authorized on the box
# (Hetzner Robot -> Storage Box -> SSH keys, or place it in the box's
# ~/.ssh/authorized_keys via sftp). Until then this prints a clear error.
#
#   sudo ./scripts/sync-site.sh     (also called automatically by deploy.sh)
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."
[ -f .env ] && set -a && source .env && set +a

SRC="${HETZNER_SYNC_SRC:-}"
DEST="${HETZNER_SYNC_DEST:-}"
USER="${HETZNER_SYNC_USER:-}"
HOST="${HETZNER_SYNC_HOST:-}"
PORT="${HETZNER_SYNC_PORT:-23}"
KEY="${HETZNER_SYNC_KEY:-/home/ryan/.ssh/hetzner_backup}"

if [ -z "$SRC" ] || [ -z "$DEST" ] || [ -z "$USER" ] || [ -z "$HOST" ]; then
  echo "HETZNER_SYNC_* not configured in .env — skipping site import."
  exit 0
fi

if [ ! -f "$KEY" ]; then
  echo "!! Missing SSH key $KEY"
  echo "   Run: sudo bash scripts/host-setup.sh   (generates the key and prints the .pub)"
  exit 1
fi

echo "==> importing $USER@$HOST:$SRC -> $DEST"
mkdir -p "$DEST"

if ! rsync -az --delete \
     --exclude='*.log' \
     --exclude='.cache' \
     --exclude='lost+found' \
     -e "ssh -i $KEY -p $PORT -o StrictHostKeyChecking=accept-new" \
     "$USER@$HOST:$SRC/" "$DEST/"; then
  echo
  echo "!! rsync failed — the Hetzner box rejected the connection."
  echo "   The public key must be authorized on the box (one-time, manual):"
  echo "     Hetzner Robot -> Storage Box -> SSH keys -> paste:"
  echo "       $(cat "$KEY.pub" 2>/dev/null || echo "(key not readable)")"
  echo "   (or one-time sftp -P $PORT $USER@$HOST and place the .pub in ~/.ssh/authorized_keys)"
  echo "   Then re-run: sudo bash scripts/sync-site.sh"
  exit 1
fi

"$PWD/scripts/fix-perms.sh" "$DEST"
echo "Imported."